#ifndef __NXVIDEOSINGLETON_H__
#define __NXVIDEOSINGLETON_H__

#include "NxVideo_Prerequisites.h"

#if NXVIDEO_COMPILER == NXVIDEO_COMPILER_MSVC

// Save warnings state
#   pragma warning (push)
// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4503)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning (disable : 4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning (disable : 4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception
// specifications in the ANSI C++ draft.
#   pragma warning( disable : 4290 )

// disable: "no suitable definition provided for explicit template
// instantiation request" Occurs in VC7 for no justifiable reason on all
// #includes of Singleton
#   pragma warning( disable: 4661)

// disable: deprecation warnings when using CRT calls in VC8
// These show up on all C runtime lib code in VC8, disable since they clutter
// the warnings with things we may not be able to do anything about (e.g.
// generated code from nvparse etc). I doubt very much that these calls
// will ever be actually removed from VC anyway, it would break too much code.
#	pragma warning( disable: 4996)

// disable: "conditional expression constant", always occurs on 
// OGRE_MUTEX_CONDITIONAL when no threading enabled
#   pragma warning (disable : 201)

// disable: "unreferenced formal parameter"
// Many versions of VC have bugs which generate this error in cases where they shouldn't
#   pragma warning (disable : 4100)

#endif

#if NXVIDEO_COMPILER == NXVIDEO_COMPILER_MSVC
// Turn off warnings generated by this singleton implementation
#   pragma warning (disable : 4311)
#   pragma warning (disable : 4312)
#endif

#if defined ( NXVIDEO_GCC_VISIBILITY )
#   pragma GCC visibility push(default)
#endif

namespace NxVideo_Namespace {

	// Template class for creating single-instance global classes. 
	template <typename T> class Singleton  
	{
	protected:
		static T* msSingleton;
	public:
		Singleton( void )
		{
			assert( !msSingleton );
#if defined( _MSC_VER ) && _MSC_VER < 1200	 
			int offset = (int)(T*)1 - (int)(Singleton <T>*)(T*)1;
			msSingleton = (T*)((int)this + offset);
#else
			msSingleton = static_cast< T* >( this );
#endif
		}

		~Singleton( void )
		{  
			assert( msSingleton );
			msSingleton = 0;  
		}

		static T& getSingleton( void )
		{	
			assert( msSingleton );
			return ( *msSingleton ); 
		}

		static T * getSingletonPtr( void )
		{ 
			return msSingleton; 
		}
	};

}

#if defined ( NXVIDEO_GCC_VISIBILITY )
#   pragma GCC visibility pop
#endif

#if NXVIDEO_COMPILER == NXVIDEO_COMPILER_MSVC
#   pragma warning (pop)// restore previous warnings settings
#endif

#endif