/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#include "NxGraphics_Headers.h"
#include "NxDevice_Headers.h"
#include "NxSound_Headers.h"
#include "NxVideo_Headers.h"
#include "NxMocap_Headers.h"
#include "NxNetwork_Headers.h"

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif

 
 

#ifdef __cplusplus
}
#endif
#endif