/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "NxNetwork_Headers.h"

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_fmod_threed_Example_CreateEngine(JNIEnv *env, jobject );
JNIEXPORT void JNICALL Java_org_fmod_threed_Example_DeleteEngine(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif