/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "NxDevice_Headers.h"

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif

	JNIEXPORT void JNICALL Java_nx_graphics_device_NxDevice_createNxDevice( JNIEnv * env, jobject obj );
 

#ifdef __cplusplus
}
#endif
#endif