/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "NxDevice_Headers.h"

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif

 
 

#ifdef __cplusplus
}
#endif
#endif